/**
 * HuggingFace parity test for `PrivacyFilter.classify`.
 *
 * This test compares our per-token argmax tag sequence against the
 * HuggingFace `transformers` reference on a small set of committed
 * fixtures. It is **doubly gated**:
 *
 *   1. `PRIVACY_FILTER_PARITY=1` opts in (parity is slow and requires
 *      model weights, so we don't want it in the default test run).
 *   2. `PRIVACY_FILTER_MODEL_DIR` must point at a valid checkpoint
 *      directory (matches the rest of the privacy test suite).
 *
 * ## Why per-token argmax (and not entity spans)?
 *
 * The HF checkpoint (`OpenAIPrivacyFilterForTokenClassification`)
 * ships only a logits head — there is no Viterbi decoder on the
 * HF side, and the `viterbi_calibration.json` file is consumed by
 * *us*, not by HF. Comparing entity spans (e.g. via HF's `pipeline(
 * 'token-classification', aggregation_strategy='simple')`) would
 * compare our Viterbi output to HF's naive BIO aggregator, which
 * disagrees on multi-word BIOES entities in benign ways and would
 * make the test flaky.
 *
 * The well-defined cross-implementation invariant is the per-token
 * argmax tag sequence over raw logits. Our `classify(text,
 * { returnTokens: true })` exposes that via `Token.tag`, which is
 * the BIOES tag of the argmax class id for each token. The fixtures
 * are generated by `scripts/dump-privacy-filter-parity.py` from the
 * HF model (CPU, fp32) and committed for reproducibility.
 *
 * ## Tolerance for bf16 vs fp32 boundary flips
 *
 * Our Rust forward pass runs in bf16; the fixtures were dumped in
 * fp32. On low-confidence tokens (typically at the boundary of an
 * entity), the argmax can flip between adjacent tag IDs purely from
 * precision differences. The flips we observe fall into three
 * categories, ordered by severity:
 *
 *   1. Label-class flip (e.g. `B-private_email` → `B-private_phone`).
 *      Real classification error. Never tolerated.
 *   2. Edge-on / edge-off (e.g. `O` ↔ any non-O, or non-O ↔ `O`).
 *      A boundary token gained or lost an entity tag. Tolerated up
 *      to `EDGE_FLIP_BUDGET` per fixture — covers the few O-tokens
 *      adjacent to an entity that bf16 vs fp32 disagree on.
 *   3. Same-class BIOES prefix flip (e.g. `B-foo` ↔ `I-foo`,
 *      `E-foo` ↔ `I-foo`). Same entity class, different position
 *      tag — sub-classification disagreement, not a bug. Tolerated
 *      up to `PREFIX_FLIP_BUDGET` per fixture.
 *
 * We assert:
 *
 *   - Token counts and byte offsets match exactly (same tokenizer
 *     on both sides — must be byte-identical).
 *   - Zero label-class flips (mismatched entity classes are real
 *     drift and must be investigated).
 *   - At most `EDGE_FLIP_BUDGET` edge-flips per fixture.
 *   - At most `PREFIX_FLIP_BUDGET` same-class prefix-flips per
 *     fixture.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { PrivacyFilter } from '@mlx-node/privacy';
import { describe, expect, it } from 'vite-plus/test';

interface FixtureToken {
  text: string;
  tag: string;
  start: number;
  end: number;
}

interface Fixture {
  input: string;
  tokens: FixtureToken[];
}

const PARITY = process.env.PRIVACY_FILTER_PARITY === '1';
const MODEL_DIR = process.env.PRIVACY_FILTER_MODEL_DIR;
const enabled = PARITY && !!MODEL_DIR;

// Per-fixture flip budgets. Tuned to absorb bf16 vs fp32 precision
// noise on boundary tokens without masking real regressions. Bumping
// either of these is a signal something has drifted — investigate
// before raising the limit.
const EDGE_FLIP_BUDGET = 2;
const PREFIX_FLIP_BUDGET = 2;

function labelClass(tag: string): string {
  // 'O' → 'O'; 'B-private_email' → 'private_email'; etc.
  if (tag === 'O') return 'O';
  const dash = tag.indexOf('-');
  return dash >= 0 ? tag.slice(dash + 1) : tag;
}

describe.skipIf(!enabled)('HuggingFace parity fixtures', () => {
  // Resolve the fixtures path relative to this test file so the test
  // works regardless of the cwd vitest is invoked from.
  const fixturesPath = join(import.meta.dirname, 'parity-fixtures.json');
  const fixtures = JSON.parse(readFileSync(fixturesPath, 'utf-8')) as Fixture[];

  it('argmax tag sequence matches HF reference per fixture', async () => {
    const pf = await PrivacyFilter.load(MODEL_DIR!);

    const fixtureFailures: string[] = [];

    for (const fx of fixtures) {
      const { tokens: actual = [] } = await pf.classify(fx.input, {
        returnTokens: true,
      });

      // Tokenizer parity: token count and byte offsets MUST match
      // exactly (we ship the same tokenizer.json on both sides).
      if (actual.length !== fx.tokens.length) {
        fixtureFailures.push(
          `[${fx.input!}] token count mismatch: ` + `actual=${actual.length} expected=${fx.tokens.length}`,
        );
        continue;
      }

      let edgeFlips = 0;
      let prefixFlips = 0;
      const tagMismatches: string[] = [];

      for (let i = 0; i < fx.tokens.length; i++) {
        const exp = fx.tokens[i]!;
        const act = actual[i]!;

        if (act.start !== exp.start || act.end !== exp.end) {
          tagMismatches.push(
            `  token[${i}] offset mismatch: ` +
              `actual=(${act.start},${act.end}) ` +
              `expected=(${exp.start},${exp.end})`,
          );
          continue;
        }

        if (act.tag === exp.tag) continue;

        const expClass = labelClass(exp.tag);
        const actClass = labelClass(act.tag);

        if (expClass === actClass) {
          // Same-class BIOES prefix flip (B↔I, E↔I, etc.).
          prefixFlips++;
          continue;
        }

        if (expClass === 'O' || actClass === 'O') {
          // Edge-on / edge-off boundary flip.
          edgeFlips++;
          continue;
        }

        // Different non-O label classes → real classification drift.
        tagMismatches.push(
          `  token[${i}] (${JSON.stringify(act.text)}) ` +
            `label-class mismatch: actual=${act.tag} expected=${exp.tag}`,
        );
      }

      if (edgeFlips > EDGE_FLIP_BUDGET) {
        tagMismatches.push(`  exceeded edge-flip budget: ${edgeFlips} > ${EDGE_FLIP_BUDGET}`);
      }
      if (prefixFlips > PREFIX_FLIP_BUDGET) {
        tagMismatches.push(`  exceeded prefix-flip budget: ${prefixFlips} > ${PREFIX_FLIP_BUDGET}`);
      }

      if (tagMismatches.length > 0) {
        fixtureFailures.push(`[${fx.input}]\n${tagMismatches.join('\n')}`);
      }
    }

    if (fixtureFailures.length > 0) {
      throw new Error(
        `HuggingFace parity failed on ${fixtureFailures.length} ` + `fixture(s):\n\n${fixtureFailures.join('\n\n')}`,
      );
    }

    // Sanity: we ran the right number of fixtures.
    expect(fixtures.length).toBe(5);
  });
});
