approvedGitRepositories:
  - "**"

catalog:
  "@types/node": "npm:@types/node@24.12.2"
  vite: "npm:@voidzero-dev/vite-plus-core@0.1.24"
  vite-plus: 0.1.24
  vitest: "npm:@voidzero-dev/vite-plus-test@0.1.24"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
