// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null;
const loadErrors = [];

const isMusl = () => {
  let musl = false;
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem();
    if (musl === null) {
      musl = isMuslFromReport();
    }
    if (musl === null) {
      musl = isMuslFromChildProcess();
    }
  }
  return musl;
};

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-');

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl');
  } catch {
    return null;
  }
};

const isMuslFromReport = () => {
  let report = null;
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true;
    report = process.report.getReport();
  }
  if (!report) {
    return null;
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false;
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true;
    }
  }
  return false;
};

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl');
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false;
  }
};

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err);
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.android-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-android-arm64');
        const bindingPackageVersion = require('@mlx-node/core-android-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./mlx-core.android-arm-eabi.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-android-arm-eabi');
        const bindingPackageVersion = require('@mlx-node/core-android-arm-eabi/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`));
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (
        process.config?.variables?.shlib_suffix === 'dll.a' ||
        process.config?.variables?.node_target_type === 'shared_library'
      ) {
        try {
          return require('./mlx-core.win32-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-win32-x64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-win32-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.win32-x64-msvc.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-win32-x64-msvc');
          const bindingPackageVersion = require('@mlx-node/core-win32-x64-msvc/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./mlx-core.win32-ia32-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-win32-ia32-msvc');
        const bindingPackageVersion = require('@mlx-node/core-win32-ia32-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.win32-arm64-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-win32-arm64-msvc');
        const bindingPackageVersion = require('@mlx-node/core-win32-arm64-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`));
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./mlx-core.darwin-universal.node');
    } catch (e) {
      loadErrors.push(e);
    }
    try {
      const binding = require('@mlx-node/core-darwin-universal');
      const bindingPackageVersion = require('@mlx-node/core-darwin-universal/package.json').version;
      if (
        bindingPackageVersion !== '0.0.7' &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
      ) {
        throw new Error(
          `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
        );
      }
      return binding;
    } catch (e) {
      loadErrors.push(e);
    }
    if (process.arch === 'x64') {
      try {
        return require('./mlx-core.darwin-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-darwin-x64');
        const bindingPackageVersion = require('@mlx-node/core-darwin-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.darwin-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-darwin-arm64');
        const bindingPackageVersion = require('@mlx-node/core-darwin-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`));
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./mlx-core.freebsd-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-freebsd-x64');
        const bindingPackageVersion = require('@mlx-node/core-freebsd-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.freebsd-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-freebsd-arm64');
        const bindingPackageVersion = require('@mlx-node/core-freebsd-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`));
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-x64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-x64-musl');
          const bindingPackageVersion = require('@mlx-node/core-linux-x64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-x64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-linux-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-arm64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-arm64-musl');
          const bindingPackageVersion = require('@mlx-node/core-linux-arm64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-arm64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-arm64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-linux-arm64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-arm-musleabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-arm-musleabihf');
          const bindingPackageVersion = require('@mlx-node/core-linux-arm-musleabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-arm-gnueabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-arm-gnueabihf');
          const bindingPackageVersion = require('@mlx-node/core-linux-arm-gnueabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-loong64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-loong64-musl');
          const bindingPackageVersion = require('@mlx-node/core-linux-loong64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-loong64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-loong64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-linux-loong64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-riscv64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-riscv64-musl');
          const bindingPackageVersion = require('@mlx-node/core-linux-riscv64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-riscv64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-riscv64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-linux-riscv64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./mlx-core.linux-ppc64-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-linux-ppc64-gnu');
        const bindingPackageVersion = require('@mlx-node/core-linux-ppc64-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./mlx-core.linux-s390x-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-linux-s390x-gnu');
        const bindingPackageVersion = require('@mlx-node/core-linux-s390x-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`));
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.openharmony-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-openharmony-arm64');
        const bindingPackageVersion = require('@mlx-node/core-openharmony-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./mlx-core.openharmony-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-openharmony-x64');
        const bindingPackageVersion = require('@mlx-node/core-openharmony-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./mlx-core.openharmony-arm.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-openharmony-arm');
        const bindingPackageVersion = require('@mlx-node/core-openharmony-arm/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`));
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`));
  }
}

nativeBinding = requireNative();

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null;
  let wasiBindingError = null;
  try {
    wasiBinding = require('./mlx-core.wasi.cjs');
    nativeBinding = wasiBinding;
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err;
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@mlx-node/core-wasm32-wasi');
      nativeBinding = wasiBinding;
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err;
        } else {
          wasiBindingError.cause = err;
        }
        loadErrors.push(err);
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error');
    error.cause = wasiBindingError;
    throw error;
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err;
          return cur;
        }),
      },
    );
  }
  throw new Error(`Failed to load native binding`);
}

module.exports = nativeBinding;
module.exports.BatchGenerationResult = nativeBinding.BatchGenerationResult;
module.exports.ChatStreamHandle = nativeBinding.ChatStreamHandle;
module.exports.DocLayoutModel = nativeBinding.DocLayoutModel;
module.exports.PPDocLayoutV3Model = nativeBinding.PPDocLayoutV3Model;
module.exports.DocOrientationModel = nativeBinding.DocOrientationModel;
module.exports.DocUnwarpModel = nativeBinding.DocUnwarpModel;
module.exports.Gemma4Model = nativeBinding.Gemma4Model;
module.exports.GenerationResult = nativeBinding.GenerationResult;
module.exports.GrpoTrainingEngine = nativeBinding.GrpoTrainingEngine;
module.exports.GRPOTrainingEngine = nativeBinding.GRPOTrainingEngine;
module.exports.HarrierModel = nativeBinding.HarrierModel;
module.exports.Lfm2Model = nativeBinding.Lfm2Model;
module.exports.MxArray = nativeBinding.MxArray;
module.exports.NativeRewardRegistry = nativeBinding.NativeRewardRegistry;
module.exports.OutputStore = nativeBinding.OutputStore;
module.exports.PrivacyFilterModel = nativeBinding.PrivacyFilterModel;
module.exports.PrivacyFilterModelJs = nativeBinding.PrivacyFilterModelJs;
module.exports.QianfanOCRModel = nativeBinding.QianfanOCRModel;
module.exports.Qwen35Model = nativeBinding.Qwen35Model;
module.exports.Qwen3_5Model = nativeBinding.Qwen3_5Model;
module.exports.Qwen35MoeModel = nativeBinding.Qwen35MoeModel;
module.exports.Qwen3_5MoeModel = nativeBinding.Qwen3_5MoeModel;
module.exports.Qwen3Model = nativeBinding.Qwen3Model;
module.exports.Qwen3Tokenizer = nativeBinding.Qwen3Tokenizer;
module.exports.ResponseStore = nativeBinding.ResponseStore;
module.exports.SftTrainingEngine = nativeBinding.SftTrainingEngine;
module.exports.Tensor = nativeBinding.Tensor;
module.exports.TextDetModel = nativeBinding.TextDetModel;
module.exports.TextRecModel = nativeBinding.TextRecModel;
module.exports.VlmChatResult = nativeBinding.VlmChatResult;
module.exports.VLMChatResult = nativeBinding.VLMChatResult;
module.exports.VLModel = nativeBinding.VLModel;
module.exports.VlmProcessedImage = nativeBinding.VlmProcessedImage;
module.exports.abs = nativeBinding.abs;
module.exports.add = nativeBinding.add;
module.exports.all = nativeBinding.all;
module.exports.any = nativeBinding.any;
module.exports.arange = nativeBinding.arange;
module.exports.arccos = nativeBinding.arccos;
module.exports.arcsin = nativeBinding.arcsin;
module.exports.arctan = nativeBinding.arctan;
module.exports.argmax = nativeBinding.argmax;
module.exports.argmin = nativeBinding.argmin;
module.exports.argsort = nativeBinding.argsort;
module.exports.astype = nativeBinding.astype;
module.exports.besselI0e = nativeBinding.besselI0e;
module.exports.besselI1e = nativeBinding.besselI1e;
module.exports.broadcastTo = nativeBinding.broadcastTo;
module.exports.buildRewardOutputs = nativeBinding.buildRewardOutputs;
module.exports.BuiltinRewardType = nativeBinding.BuiltinRewardType;
module.exports.ceil = nativeBinding.ceil;
module.exports.ChatRole = nativeBinding.ChatRole;
module.exports.cholesky = nativeBinding.cholesky;
module.exports.choleskyInv = nativeBinding.choleskyInv;
module.exports.clearCache = nativeBinding.clearCache;
module.exports.clip = nativeBinding.clip;
module.exports.compileClearCache = nativeBinding.compileClearCache;
module.exports.concatenate = nativeBinding.concatenate;
module.exports.convertForeignWeights = nativeBinding.convertForeignWeights;
module.exports.convertGgufToSafetensors = nativeBinding.convertGgufToSafetensors;
module.exports.convertModel = nativeBinding.convertModel;
module.exports.convertParquetToJsonl = nativeBinding.convertParquetToJsonl;
module.exports.cos = nativeBinding.cos;
module.exports.cosh = nativeBinding.cosh;
module.exports.createPaddleocrVlConfig = nativeBinding.createPaddleocrVlConfig;
module.exports.createQianfanOcrConfig = nativeBinding.createQianfanOcrConfig;
module.exports.createRandomQwen35Checkpoint = nativeBinding.createRandomQwen35Checkpoint;
module.exports.createRandomQwen35MoeCheckpoint = nativeBinding.createRandomQwen35MoeCheckpoint;
module.exports.createRandomQwen3Checkpoint = nativeBinding.createRandomQwen3Checkpoint;
module.exports.cumprod = nativeBinding.cumprod;
module.exports.cumsum = nativeBinding.cumsum;
module.exports.diag = nativeBinding.diag;
module.exports.digamma = nativeBinding.digamma;
module.exports.div = nativeBinding.div;
module.exports.documentToXlsx = nativeBinding.documentToXlsx;
module.exports.DType = nativeBinding.DType;
module.exports.dtypeOf = nativeBinding.dtypeOf;
module.exports.eigh = nativeBinding.eigh;
module.exports.eigvalsh = nativeBinding.eigvalsh;
module.exports.einsum = nativeBinding.einsum;
module.exports.ElementType = nativeBinding.ElementType;
module.exports.equal = nativeBinding.equal;
module.exports.erf = nativeBinding.erf;
module.exports.erfinv = nativeBinding.erfinv;
module.exports.evalArrays = nativeBinding.evalArrays;
module.exports.exp = nativeBinding.exp;
module.exports.expandDims = nativeBinding.expandDims;
module.exports.expm1 = nativeBinding.expm1;
module.exports.eye = nativeBinding.eye;
module.exports.flatten = nativeBinding.flatten;
module.exports.floor = nativeBinding.floor;
module.exports.floorDivide = nativeBinding.floorDivide;
module.exports.formatDocument = nativeBinding.formatDocument;
module.exports.fromFloat32 = nativeBinding.fromFloat32;
module.exports.fromInt32 = nativeBinding.fromInt32;
module.exports.full = nativeBinding.full;
module.exports.getActiveMemory = nativeBinding.getActiveMemory;
module.exports.getCacheMemory = nativeBinding.getCacheMemory;
module.exports.getMemoryLimit = nativeBinding.getMemoryLimit;
module.exports.getMemorySnapshot = nativeBinding.getMemorySnapshot;
module.exports.getNumResources = nativeBinding.getNumResources;
module.exports.getPeakMemory = nativeBinding.getPeakMemory;
module.exports.getProfilingData = nativeBinding.getProfilingData;
module.exports.getResourceLimit = nativeBinding.getResourceLimit;
module.exports.getWiredLimit = nativeBinding.getWiredLimit;
module.exports.gpuArchitectureGen = nativeBinding.gpuArchitectureGen;
module.exports.greater = nativeBinding.greater;
module.exports.greaterEqual = nativeBinding.greaterEqual;
module.exports.inner = nativeBinding.inner;
module.exports.isfinite = nativeBinding.isfinite;
module.exports.isinf = nativeBinding.isinf;
module.exports.isnan = nativeBinding.isnan;
module.exports.isProfilingEnabled = nativeBinding.isProfilingEnabled;
module.exports.item = nativeBinding.item;
module.exports.keyBernoulli = nativeBinding.keyBernoulli;
module.exports.keyCategorical = nativeBinding.keyCategorical;
module.exports.keyGumbel = nativeBinding.keyGumbel;
module.exports.keyLaplace = nativeBinding.keyLaplace;
module.exports.keyMultivariateNormal = nativeBinding.keyMultivariateNormal;
module.exports.keyNormal = nativeBinding.keyNormal;
module.exports.keyRandint = nativeBinding.keyRandint;
module.exports.keyTruncatedNormal = nativeBinding.keyTruncatedNormal;
module.exports.keyUniform = nativeBinding.keyUniform;
module.exports.less = nativeBinding.less;
module.exports.lessEqual = nativeBinding.lessEqual;
module.exports.lgamma = nativeBinding.lgamma;
module.exports.linalgInv = nativeBinding.linalgInv;
module.exports.linalgNorm = nativeBinding.linalgNorm;
module.exports.linalgSolve = nativeBinding.linalgSolve;
module.exports.linspace = nativeBinding.linspace;
module.exports.loadSafetensors = nativeBinding.loadSafetensors;
module.exports.log = nativeBinding.log;
module.exports.log10 = nativeBinding.log10;
module.exports.log1p = nativeBinding.log1p;
module.exports.log2 = nativeBinding.log2;
module.exports.logaddexp = nativeBinding.logaddexp;
module.exports.logcumsumexp = nativeBinding.logcumsumexp;
module.exports.logicalAnd = nativeBinding.logicalAnd;
module.exports.logicalNot = nativeBinding.logicalNot;
module.exports.logicalOr = nativeBinding.logicalOr;
module.exports.logSoftmax = nativeBinding.logSoftmax;
module.exports.logsumexp = nativeBinding.logsumexp;
module.exports.matmul = nativeBinding.matmul;
module.exports.max = nativeBinding.max;
module.exports.maximum = nativeBinding.maximum;
module.exports.mean = nativeBinding.mean;
module.exports.memoryStats = nativeBinding.memoryStats;
module.exports.metalDeviceInfo = nativeBinding.metalDeviceInfo;
module.exports.metalIsAvailable = nativeBinding.metalIsAvailable;
module.exports.min = nativeBinding.min;
module.exports.minimum = nativeBinding.minimum;
module.exports.mul = nativeBinding.mul;
module.exports.nanToNum = nativeBinding.nanToNum;
module.exports.ndimOf = nativeBinding.ndimOf;
module.exports.negative = nativeBinding.negative;
module.exports.notEqual = nativeBinding.notEqual;
module.exports.ones = nativeBinding.ones;
module.exports.outer = nativeBinding.outer;
module.exports.OutputFormat = nativeBinding.OutputFormat;
module.exports.pad = nativeBinding.pad;
module.exports.parsePaddleResponse = nativeBinding.parsePaddleResponse;
module.exports.parseToolCallsFromText = nativeBinding.parseToolCallsFromText;
module.exports.parseVlmOutput = nativeBinding.parseVlmOutput;
module.exports.power = nativeBinding.power;
module.exports.prod = nativeBinding.prod;
module.exports.qr = nativeBinding.qr;
module.exports.randomKey = nativeBinding.randomKey;
module.exports.randomSplit = nativeBinding.randomSplit;
module.exports.randomSplitN = nativeBinding.randomSplitN;
module.exports.reciprocal = nativeBinding.reciprocal;
module.exports.remainder = nativeBinding.remainder;
module.exports.repeat = nativeBinding.repeat;
module.exports.resetPeakMemory = nativeBinding.resetPeakMemory;
module.exports.resetPeakMemory = nativeBinding.resetPeakMemory;
module.exports.resetProfilingData = nativeBinding.resetProfilingData;
module.exports.reshape = nativeBinding.reshape;
module.exports.rmsNorm = nativeBinding.rmsNorm;
module.exports.roll = nativeBinding.roll;
module.exports.rope = nativeBinding.rope;
module.exports.round = nativeBinding.round;
module.exports.saveToXlsx = nativeBinding.saveToXlsx;
module.exports.scalar = nativeBinding.scalar;
module.exports.scalarInt = nativeBinding.scalarInt;
module.exports.scaledDotProductAttention = nativeBinding.scaledDotProductAttention;
module.exports.searchsorted = nativeBinding.searchsorted;
module.exports.setCacheLimit = nativeBinding.setCacheLimit;
module.exports.setMemoryLimit = nativeBinding.setMemoryLimit;
module.exports.setProfilingEnabled = nativeBinding.setProfilingEnabled;
module.exports.setWiredLimit = nativeBinding.setWiredLimit;
module.exports.shapeOf = nativeBinding.shapeOf;
module.exports.sigmoid = nativeBinding.sigmoid;
module.exports.sign = nativeBinding.sign;
module.exports.silu = nativeBinding.silu;
module.exports.sin = nativeBinding.sin;
module.exports.sinh = nativeBinding.sinh;
module.exports.sizeOf = nativeBinding.sizeOf;
module.exports.slice = nativeBinding.slice;
module.exports.softmax = nativeBinding.softmax;
module.exports.solveTriangular = nativeBinding.solveTriangular;
module.exports.sort = nativeBinding.sort;
module.exports.split = nativeBinding.split;
module.exports.sqrt = nativeBinding.sqrt;
module.exports.square = nativeBinding.square;
module.exports.squeeze = nativeBinding.squeeze;
module.exports.stack = nativeBinding.stack;
module.exports.std = nativeBinding.std;
module.exports.stopGradient = nativeBinding.stopGradient;
module.exports.sub = nativeBinding.sub;
module.exports.sum = nativeBinding.sum;
module.exports.svd = nativeBinding.svd;
module.exports.synchronize = nativeBinding.synchronize;
module.exports.take = nativeBinding.take;
module.exports.takeAlongAxis = nativeBinding.takeAlongAxis;
module.exports.tan = nativeBinding.tan;
module.exports.tanh = nativeBinding.tanh;
module.exports.tile = nativeBinding.tile;
module.exports.topk = nativeBinding.topk;
module.exports.trace = nativeBinding.trace;
module.exports.transpose = nativeBinding.transpose;
module.exports.triInv = nativeBinding.triInv;
module.exports.var = nativeBinding.var;
module.exports.where = nativeBinding.where;
module.exports.zeros = nativeBinding.zeros;
module.exports.__internal__ = nativeBinding.__internal__;
